
info:
  component: Turbine

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 8989

management:
  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'

turbine:
  app-config: ACCOUNT-CASE-SERVICE, CLIENT-ACCOUNT-SERVICE
  cluster-name-expression: new String("default")

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/